# Instalação

## Arquitetura

```{r}
knitr::include_url("https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=arquitetura.drawio#R7V1rc9o6Gv41mfMpHt0vH3Nre2bb3e6mM2d2vznggLcGs8Y0SX%2F9SsYGXwTGxjKEmM40IFuyLOl93qteXeG72evnyF1Mv4VjL7hCYPx6he%2BvEIJMQPVHl7ytSwgD64JJ5I%2FTm7YFj%2F5vLy3Mblv5Y29ZuDEOwyD2F8XCUTife6O4UOZGUfhSvO05DIpPXbgTr1LwOHKDaulf%2FjierksFBdvyL54%2FmWZPhiC9MnOzm9OC5dQdhy%2B5Ivxwhe%2BiMIzX32avd16gBy8bl3W9TzuubjoWefP4kAr3X%2FC%2Fg6ffweo38f5kn%2BcgHP%2B%2BTlv55Qar9IWvEAtUe7dj%2F5fudPyWjgT730r39PZlPQo36iLD0IECisWr%2BqEuqf%2Bn6Vjoy5A4IHfpJYzG10%2BR5%2F5cX06%2BXuvSbePq2yT9m%2BuEG%2FiTeaETgfcc7661XLhzY9%2Bfw3l8%2FezO%2FOBt3Qd1yZ0tkqoYE%2FXXjXw3qJRu3iH2XuPrsTcKIzf2w%2Fm6kXk49zZ3JI9YJss4GQOUG4HAn3vX%2BRECLd6hvguVx0CiO1F%2B0re3KJ4q0kLgOqGf2UJ1Xa0l3dDYW5NUHIXq8WmX1NJa96rY093FyeztL0WFd0SKRhb6a5SQ8u2GZPSbLVVnfm6IEOnp9IPgLgzCKKmMPyWfzZ25K%2BuPuhIu3JEfayhSdOroVqfxLNA%2F1dd5gG6j9GG%2FvCj2FQrcpEsvDvV6yBZisvySORr588nX5Ne9cCRQ%2F%2BD2wr9SXGDboh%2B6nXuYPDotug3jOJzpBjR1Tf3Ye1QX9Ci8KEhVZZPAf35%2B%2B3Ocdq1K9xkRqz57r7miFAc%2Be%2BHMi6M3dUt69ZpxtK6TojJEbP37ZYtxjKTANc3hG%2BZpoZvi6mTT%2BBZ61JcUfRogEToQif7IARCizNEEpqaxijtqMHcjDr79o2%2BsuUmgpQZGdmLILgBJetIdhuwBENOTbtRKnWqs%2BBHORq4aJiAd4IisA0%2FR4WAxYIhuAjrEJn7grvADl%2FBDigp%2BIG7AD4ihJfzAx0gyql8FWSW%2F%2BAkaxJgzFmPu3dh9Vu%2BrbvjLe3IXC7vgczZTWX7UZ08R9Mh3Z4qsQy3C6f9Wy9XVHb66gZEfXtbrPnqTVaSeot%2BOuzXvZlwKF8RZZv54rDtZw1yAQ83MpYZr0K64BixyDYSrUidCtMo1OLXENEgLoVPiVLzMYxMSncqcI62HRYPUaZY679zl0p2PI0X2ADtKZkJ7Cf3DCpwVWEiXVVVzzYmTDXCBd4ULJWkS0youbOxqeVwQtpRRunOS9fR544exthoaZrcyiyD5lOY9XfTL2I3iG22kLJV98nV30wWkfqdmUT0l3nyc1XgKwtHPdVFaAa5%2F5W6PwtV87I3Ta7m5k%2FpW9RaP6SuGUTwNJ%2BHcDR62pbtndxmuopFXL46r3k%2B8uB6BvXHBDFtdK7mlQKoLgaXdirxAYcuvou3WtDqSB6iBdN9yNyxCfx4vc8%2F%2FrgtyC5Vy5hCOmcSCcEZZadlCWDTANqyOmMIypTVBAhmAKQ20bYwoVEQUc9UrQig%2BrmeUORgLwDHHgDCRsuMtga0Hcktum3lrT4HsGHVODaOD%2BrdKd8e1P7JC98n9FUZ%2BrJjocmDrx7F10oqtQ9gRXyfiAL6OjFZmS3ydD6jSAFWsY8aBiGDW9QdQ6BUUujIdV0BByhODguhf2M9E97y0Dy1K%2B5BaFvfJgeI%2Bay7uU15dCz2J%2B2W9lEuHKHmacgqlkqlRQQ421IfUwUBJ1JBxuRGb27ZGpHAYZJJgTCU%2BtjEBHYkogRRgCRhq0podgV9%2BACoUx1FhIyVZdEQ1prVTJAsCuSMwB5hBjES2WDYtrrEjbWQvuWDkAE6oIJKBygqvecoaeSpPaU7zgDtAqc1SjWBO193fC6uEkUXCtRRaAXLYDqE1NVpfltB6Sarw93AZTyLv8Z9fE%2FVjkHyPk3xRK8kXdaUO4wOCJiA0SL7UlpkbHhn%2BiR2iPrvg5SJ14kuCl1wE6GMYRHdBuFJzAe6C1XI9umeDNkWRyo1GqbiV6DXu0zIMVrF3sy0%2BC4D66j55gYJwfz1LafxXGb6e0vCtOvjiDl9%2F2oFYZz78UuQoJQdGjkJrkaNZVEGz0FEFXmIIHT2dE18jzihFnL%2BHScD5IOC0jRvlTi5G1ELYKOoKPWgJPZghAsiIHtgaehwVOMqpw3f5BAb16szln030usYi9UfHwQwIZECgQ1UsBUOklXiCuwslkk7RYsMAzkpyIJOZsHqJMoStwgwVWlcFlA8VZ7hTdvhPqFa4t9A9V7NLHAgGcjSSo9whFtSRo%2ByIHCniBxCjNNiq7RHj5cf2EQ3CNr198FB3XyZcNfFcYOoIxYslg0QwAZkh3A86RCbBbQwASilJwdy2O7C8mEldVB3mDmSMISqToDrasDrhjoYKqAhEaGdDw%2BqUl1lhsYold8WhkXuDNn7e2vh8kIXPUxtnXe0Cx4CcnTZ%2BVITeoI0P2vjlI5B1bZyKjgAGKSX2%2FLRxMWjjgzb%2BjrRx2pXvDnJ5dtr4CcL%2BetbGqbZtWtXGxaHaOL8gbbyymOv0YSjkMdo4lLKojTesr1PjnEAd32SfqxKYqu0vlnrtKez21YM0aGWl37dFDbF2Q4e7KbSKtXn1pqudBliU7DWGJFemcCtoS7nZUPT7mYuuWA8m5zYX6N3NBetqLti5zQXuXwjoO%2FafW5cCwIFSAG2zm6C6GjDphc2jjFCznDHpYtnDZ%2Bk%2BPl1bHwrhKCmBCQ4g5LC8AaC%2BPt%2FbYUtcnlQoaKKWYkmRELYMhxgZ9vAZ078RaxiSTlPLXRIMnGJr76nyv53Lxt5iCtobhYVvSrUetv23dTxIu9kjmTksYC8iHYAqJwSN47KMKM33BLmvB29DF96Gh8Bdaqzx3Gg0HeClyTaqdlZMbt5GdSx4pFczISbbpgmq8gg2QIs1PyY6LtPIHmSxmI62NbK0oMqTEv8G4uZPy0XH4kXTwf2y8rptcOAD57IUBlawgxWYLbx2WMEmceTpeEEbh3PGAooO5xT8T%2B5wbhp3durwtnMC%2FJbK82kH8Gs4WcbucpekTB2mVM%2BzGL0PEa45cK0TcC2zL8wO1%2BInZ1qXH5ghknstumRSR0CtRyazXTfxyMBsH0shDXI%2FoRe4lB8YSeAwDKRYpxquyz2GKHEQELscNF02ljkmrDpf8O4Qi4shFWKZVLJMNFZoxRjC3hetlHe8k5q83uUKBHFHSiIxAQKBeoIo%2B%2Bb217dEEbsDXc7JoZ82s6UI0IAijszl1xnzgC3c%2BVnUZVGS6MehXz7soSHeM4ociiBHgsJKEF%2BXbZUI1RKhoAqhGPz2sqt4fEFKYw8MkT9GtAS2AoDxUek3IIYO%2BTh%2B%2B0syvN7qs5mTPQMtTiq7fG32oANnhVmR7cbbLxtYaTMca%2Bjt7xlqOjvtq%2BONyYOta5%2Bt6%2Ba%2F7utz5M5HSi55GmKDTnLSl2xg%2B2qABZntCxSVdkNaVNPpX0TaAorLTxEiz%2BX8rwyUG6kvwLBFrR91vnKEJdXb%2BpjkUorq0ViG%2BiSJLt4VXNy0NZHEOgsF3yzJ039UaxwhRy1WxiEW6j8hGrRmST2qxuc9%2BsvYm7lXSbbIS4Nnvit%2Bs%2B5wFtDRnqlsJ0bmOzfsDDFFaCKAbUHxUXFUjOyM6h7SQZy5frgl9CERzYlApaPNfyVQ0UdoVHedm2CFC1uo0ioFxKAJnlgT%2FHp%2F8z1BxU%2F6Be8HWDiFKghBV7lay25kSg7U%2B2zFPODdMQ9nuicYQtTNZNCisI8NWf173RJMdvvUz3YqOpLBy1MhTGTR51S8u6wFsKsTbMtTwU49FVV34aUZpqD1oyrxoelyWuSuFQbDFBQpW%2Bk5KouT%2FHozHONHkSOBIh9gyodzXG2Ee3CekxOkjeidGti5UEObtBEwEyOK23lpL%2FSAGtIDhPyo%2B7Pj3Oyu%2BUN9mEZ7WKrCDhuW36E97EfkP63m%2Bm3P5Jyk2etEKYdT5zkIX0ZThX%2BOmuWZP3fjsLnI9641YthRfBYkRXnTZH43asTWDogkR2VVGeDmIuAGDXBzVnCTzmTncIMYPDXcHJWPZYCbi4Cb83D3DXCzgZuOTMxluCGmpHH9wg3v34DQd95JiGzb0zKVtN6exppbELLNUAUDQh%2Fmg4osTvfnd4ZIOowSSiCo7iWprQyhg4EsbNA6tK5EjmSY6f07rBxPVqprySQhPgIV2bbDZZqWHSoy7BU%2BCRUhsX%2F3Y0JFWBKgmENlNddWVlSEuBBAUIkb1tVUBIV6vpCgYswWfRizT7Dfvn8qsp0EOVMg6qmoxVEI1OTqOwUVEbrfNJ1QEeEcUMArW%2BJrK2sqkpRirRBWOFldbU1HBCPMTeyoVNkOIWWzNGwo%2FGAq5Ob8sB%2FhbOTGVztS5AzRYue1zRDijvTLa5hFymTSL0sdxLVbDq1l0cmcpi3BCCCHDfHr7xyOvrlz%2FzkMxnefBkjq1qCFzLhUBzjmLOZtjlMrBhhkAQDFNE19GrQya8klR8QgYlmHwIfqEG0iYrgpQKwPHQJhR0n2hAIoacXGpDQGpTAQRjE%2BJMUQdRCVoHBvy5YwdphSNiBjBqtZw7bKScn21bakenyAgDRkO%2B9RppnbIT9DPNomh6JtAizpwsypW9BOWX1uXEXxYwcrXZ4wxuUB%2B4nR4bUtkVD1IKNLIyFhe%2Bt9RhhWUocZ%2FDGY9EJA15I4CArETBvnidi%2FsvfUxYQnB4ZxAtR3XEcje1pS3EZv7ufkoO32exqiqiG1diFCgPfFuy4%2F54VA50J4bZJYIpPkSFkvlFcOda4lt0oFCepY1yYpYfsqvWR7zYb84hw1Y3c53fx49l%2Fvdbr37aXvbqy0cK2PQwVO2uzB9mn1ebqzvqPHosSIKTdwvH7IjgDo6HxoECCKDX5JvN%2BnWVcf0joqxtLhAnJsyKx8XOU%2BtkrQ445gUiwYS%2FiR4gnP5lRIbSkF7ioOI3%2FsjrUNdaRAcaR%2Buyc1mWrb8G7EC9wnL7h1Rz8nCa6arKUdW0CBKaSvDL7m3fp7WdvhNlDVA6bTQSEmFZUTyTKO3AwZt%2BiR3RI%2BPy8VlpcNos1gYfa3r%2FIn%2BNf86R9fvjw%2B0PnDLb%2B9NnlkSvOcY6OjwF0u%2FVGZIW%2BLc1N6KIsrsR8Dz2schkBbaWBV0BYAO2ao3rSy5sZpxb1WQinK1ghUamvNsSttNWaU1W7zGu5U7RzvliUZ1x6qrL1Qwdy0ugK3khnY4dDIrbsdRHvQutrkfst0%2BHQ0mOH8EWRYeC1ycaifUagBfzuyOtL6Wzj29B3%2FBw%3D%3D")
```



## Implementação

A tabela abaixo, que deve ser atualizada conforme adicionamos novos elementos, lista as implementações, bem como o seu estágio.

```{r tab-imp,echo=FALSE}

tibble::tribble(
  ~Recurso, ~Implementado,
  "scraper tribunais",     "parcial",
  "crawler djes",          "sim",
  "indexação para Solr",  "sim",
  "tika-ocr",             "sim",
  "stopwords",            "parcial",
  "anotação",             "não",
  "fuzzy search",         "sim",
  "regex textos",         "sim",
  "parseamento htmls",    "parcial"
) %>% 
  knitr::kable(caption = "Implementações",
               booktabs = TRUE)

```


## 
